name: international_phone_input
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
    - assets/icons/
